name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Run benchmarks
        run: cargo bench --no-fail-fast
        continue-on-error: true
      
      - name: Performance test with 100MB random data
        run: |
          cargo build --release
          echo "Testing with 100MB of random data from /dev/urandom..."
          echo "Generating and processing 100MB..."
          time dd if=/dev/urandom bs=1M count=100 2>/dev/null | target/release/hexler --stdout --num-bytes-per-line 16 > /dev/null
          echo "Done!"
      
      - name: Performance test with sample file
        run: |
          echo "Testing with small sample file (256 bytes)..."
          time target/release/hexler tests/data/256.bin --stdout > /dev/null
