name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  smart-release:
    name: Release via cargo-smart-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-smart-release
        run: |
          cargo install --force cargo-smart-release

      - name: Run cargo-smart-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # cargo-smart-release will create the GitHub Release, build artifacts and publish to crates.io
        run: cargo smart-release
